#! /bin/bash
# vim:ts=4:sw=4:noet:ai

do_config() {
	echo "graph_category openstack"
	echo "graph_title Nova RAM allocation"
	echo "graph_vlabel Allocated RAM in MB"
	echo "graph_order physical allocated used"
	echo "graph_args --base 1024 -l 0 --vertical-label Bytes" #" --upper-limit"

	echo "physical.label physical"
	echo "physical.draw LINE2"
	echo "physical.info Physical RAM available to host node."

	echo "allocated.label allocated"
	echo "allocated.draw AREA"
	echo "allocated.info Virtual RAM allocated by virtual machine instances."

	echo "used.label used"
	echo "used.draw AREA"
	echo "used.info Virtual RAM currently used by virtual machine instances."
}

do_fetch() {
	# calculating RAM alloation
	local HOST_RAM=$(echo $[$(grep MemTotal: /proc/meminfo | awk '{print $2}') / 1024])
	local RAM=( $(ps -ef | grep /usr/bin/kvm | grep -v grep | sed 's/^.*-m \([0-9]\+\).*$/\1/') )
	local RAM_SUM=0
	for i in ${RAM[*]}; do
		RAM_SUM=$[RAM_SUM + i]
	done

	local VALUES=( $(nova-manage service describe_resource ${HOSTNAME} 2>/dev/null | grep ${HOSTNAME} | awk '{print $4}') ) 
	echo "physical.value ${VALUES[0]}"
	echo "allocated.value ${RAM_SUM}"
	echo "used.value ${VALUES[1]}"
}

case "$1" in
	config) do_config ;;
	fetch) do_fetch ;;
	*) do_fetch ;;
esac
